### ISSUE TITLE
UART for Tracer

### ISSUE THREAD

**Issue by autonomousTurtle** [westonrobot/ugv_sdk#23]
Is UART supported for the Tracer robot? The Agilex documentation mentions RS232 compatibility, but inside of [tracer_ros -> tracer_base -> src -> tracer_base_node.cpp](https://github.com/agilexrobotics/tracer_ros/blob/master/tracer_base/src/tracer_base_node.cpp), the TracerTOSMessenger::PublishUartSTateToROS() is commented out and cannot find reference in westonrobot when it is uncommented. 

Thank you

**Comment by autonomousTurtle** [comment]
I suppose I have [found the answer](https://github.com/westonrobot/ugv_sdk/blob/main/include/ugv_sdk/details/robot_base/tracer_base.hpp#:~:text=void%20Connect(std,%7D)) - line 35 TODO

**Comment by rdu-weston** [comment]
The SDK currently only supports CAN for all the robot bases.
