### ISSUE TITLE
Cannot build in ROS2 humble for hunter2_ros2

### ISSUE THREAD

**Issue by TZECHIN6** [westonrobot/ugv_sdk#24]
Posted on https://github.com/agilexrobotics/hunter_ros2/issues/9

I followed the steps shown on above `hunter_ros2` repository, however the `ugv_sdk` actually is replying on `catkin` to build... so how does you make it work in ROS2?

Details please find on the above referred link.

**Comment by rdu-weston** [comment]
Hi, I just tried to build the two packages (ugv_sdk and hunter_ros2/humble) but could not reproduce the issue you have. I did the "colcon build" both in native Ubuntu 22.04 + ROS2 Humble and in docker containers. 

You can also refer to the CI configuration here to build ugv_sdk alone: https://github.com/westonrobot/ugv_sdk/blob/main/.github/workflows/ros-ci.yml#L34

I don't think the build issue has anything related to catkin. The readme indeed needed to be updated (i.e. not catkin workspace).

Is there anything else you can share with us to reproduce the issue? Have you tried a clean build (i.e. removing build and install folder before colcon build)?

**Comment by TZECHIN6** [comment]
Oh sorry, I think I made a mistake, I have used agileX's `ugv_sdk` and not yours, I will test this out in tmr.

For the gazebo simulation, AgileX replied that ROS2 is not supported yet, have you supported the ROS2 simulation yet?

**Comment by rdu-weston** [comment]
Unfortunately, we don't have ROS2 simulation support either. Anyway, good luck with your test on the sdk issue. It should work.

**Comment by TZECHIN6** [comment]
Just to notice that the README in hunter2_ros2/humble is not updated. It points to clone the ugv_sdk from agilexrobotics and will cause error when build.

### Original instructions
```
$ cd ~/ros2_ws/src
$ git clone https://github.com/agilexrobotics/ugv_sdk.git
$ git clone https://github.com/agilexrobotics/hunter_ros2.git
$ cd ..
$ colcon build
```
