### ISSUE TITLE
Missing tracer_robot.cpp

### ISSUE THREAD

**Issue by ghokulji** [westonrobot/ugv_sdk#35]
Hi,

I am working on using the ugv_sdk and tracer_ros package. I am trying to run the ROS keyboard teleop and found that the tracer_robot.cpp is missing in ugv_sdk. When using the keyboard teleop, it is published to the /cmd_vel topic, but the robot is not moving as the command is not sent to it.

The [https://github.com/westonrobot/ugv_sdk/blob/main/include/ugv_sdk/mobile_robot/tracer_robot.hpp](url) is empty and doesn't have any 'SetMotionCommand' function. 

Can you provide the tracer_robot.cpp file,  so that I can run the ROS teleop? 
Thanks!

**Comment by rdu-weston** [comment]
Hi, first please make sure you clone the code from the following two repositories:

* https://github.com/westonrobot/ugv_sdk
* https://github.com/westonrobot/tracer_ros

It should not be the SDK issue. The necessary logic is implementation within https://github.com/westonrobot/ugv_sdk/blob/main/include/ugv_sdk/details/robot_base/tracer_base.hpp.

If you still think so, please share with us a screenshot of the compilation error from catkink_make.

Can you also check if you've switched the RC to auto mode before trying to control the robot with teleop node?

**Comment by rdu-weston** [comment]
> May I know how to switch the RC mode to auto mode?
> 
> I am not facing any issue with catkin_make. When I give the keyboard command, it moves an publishes to /cmd_vel. But the robot doesn't move.

Please refer to: https://docs.westonrobot.net/getting_started/basics/robot_base_control.html
