### ISSUE TITLE
resource deadlock error caused by sleep_until_ms

### ISSUE THREAD

**Issue by tmxkn1** [westonrobot/ugv_sdk#37]
We are implementing ROS2 on a Scout mini and encountered an error.

The Humble package for Scout mini was cloned from https://github.com/westonrobot/scout_ros2 ([commit 379c1](https://github.com/westonrobot/scout_ros2/commit/379c1ca409198a8e9558ae2af425830428b1f3d3)).

We got the following after launch scout_base.
```
$ ros2 launch scout_base scout_base.launch.py is_scout_mini:=true
[INFO] [launch]: All log files can be found below /home/iaa/.ros/log/2023-09-20-14-17-46-948703-13anki5-70206
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [scout_base_node-1]: process started with pid [70207]
[scout_base_node-1] Loading parameters: 
[scout_base_node-1] - port name: can0
[scout_base_node-1] - odom frame name: odom
[scout_base_node-1] - base frame name: base_link
[scout_base_node-1] - odom topic name: odom
[scout_base_node-1] - is scout mini: true
[scout_base_node-1] - is omni wheel: false
[scout_base_node-1] - simulated robot: false
[scout_base_node-1] - sim control rate: 50
[scout_base_node-1] ----------------------------
[scout_base_node-1] Robot base: Scout Mini
[scout_base_node-1] Start listening to port: can0
[scout_base_node-1] terminate called after throwing an instance of 'std::system_error'
[scout_base_node-1]   what():  Resource deadlock avoided
[ERROR] [scout_base_node-1]: process has died [pid 70207, exit code -6, cmd '/home/iaa/iaa-ws/install/scout_base/lib/scout_base/scout_base_node --ros-args --params-file /tmp/launch_params_fseufonr'].
```

A bit of debugging shows the error is produced at [Line 146 in stopwatch.hpp](https://github.com/westonrobot/ugv_sdk/blob/20d85ec619a477a564e2e9f2c60004a854cc4ee5/src/utilities/stopwatch.hpp#L146).

Any idea why this is happening? We did not change any code.

**Comment by rdu-weston** [comment]
Can you first check if the can0 interface is set up properly?

**Comment by tmxkn1** [comment]
> Can you first check if the can0 interface is set up properly?

I have wired up the aviation connector to the supplied CAN-USB convertor, connected the convertor to my PC with the supplied USB cable. I have also swithed on the transmitter, put all the switches (A,B,C and D) to the up position according to the manual:
>Correctly start the chassis of SCOUT MINI mobile robot, and turn on DJI RC transmitter. Then,
switch to the command control mode, i.e. toggling S1 mode of DJI RC transmitter to the top. At this
point, SCOUT MINI chassis will accept the command from CAN interface, and the host can also
parse the current state of the chassis with the real-time data fed back from CAN bus.

**Comment by rdu-weston** [comment]
Can you get any CAN data with candump?

**Comment by tmxkn1** [comment]
not sure how but probably it isn't connected properly?

```
$ candump can0
read: Network is down
```

**Comment by rdu-weston** [comment]
This means the interface is not set up properly. Please refer to this section https://github.com/westonrobot/ugv_sdk#setup-can-to-usb-adapter to set up the interface first and then try to start the ROS node again.
