### ISSUE TITLE
Error when robot connects to x86_64 host

### ISSUE THREAD

**Issue by CSU-SS** [westonrobot/ugv_sdk#43]
When I use the command "roslaunch hunter_bringup hunter_robot_base.launch" to connect to the x86_64 host, the error in the picture appears. However, when I connect to the arm64 host, no errors appear. 
![2023-12-14 21-41-38 的屏幕截图](https://github.com/westonrobot/ugv_sdk/assets/137242044/ac9961db-d70b-4790-ba2f-0c3e77c94ab9)

**Comment by rdu-weston** [comment]
I seems you're working with the ROS package, not the sdk itself. You may share which repo and branch you're using so that we can help to take a look.
