### ISSUE TITLE
Can I control motor current?

### ISSUE THREAD

**Issue by POTATOTASTE** [westonrobot/ugv_sdk#48]
I am using the AGILEX BUNKER MINI. I would like to control the torque of the motor through current control. Is it possible to do this using the ugv_sdk, or if not, what method should I use?

**Comment by rdu-weston** [comment]
Currently it's not possible because the torque control of the motors is on the motor drivers and the internal robot controller (the one that talks with your computer using this SDK) doesn't expose relevant interfaces to upper layers.

**Comment by POTATOTASTE** [comment]
Thank you for the response. so Is there a way to access the motor driver and the internal robot controller?

**Comment by rdu-weston** [comment]
At the moment, the internal communication protocol is not open to the users.

**Comment by POTATOTASTE** [comment]
Thank you for the response.
